version = 1
initial_state_len = 4
initial_state = [0, 0, 0, 24]
next_state_len = 4
next_state = [0, 0, 0, 12]
identity_len = 0
identity = ""
tx_hash_len = 4
tx_hash = [0, 0, 0, 0]
payload_hash = 0
program_outputs = "Any output heehee"