version = 1
initial_state_len = 4
initial_state = [0, 0, 0, 24]
next_state_len = 4
next_state = [0, 0, 0, 12]
origin_len = 0
origin = ""
caller_len = 0
caller = ""
block_number = 1844674407370955161
block_time = 0
tx_hash_len = 4
tx_hash = [0, 0, 0, 0] 
program_outputs = "Any output heehee"